# frozen_string_literal: true

require "json"
require "aura/kernel/narrative_service"

module Aura
  module Kernel
    # MemoryMetabolizer: Manages event lifecycle with tiered retention strategy
    #
    # Two types of summaries:
    # 1. Call Summary: Provided by LLM in tool call response (stored via StateRecorder)
    #    - Config: tool_protocol.call_summary.*
    #    - Timing: Every tool execution
    #
    # 2. Metabolism Summary: Generated by NarrativeService during metabolism
    #    - Config: state_management.summarization.*
    #    - Timing: When events exceed thresholds
    #
    # Retention Tiers (configured in state_management.retention):
    # - Tier 1 (Ephemeral): execution, observe - quickly summarized
    # - Tier 2 (Working): plan, user - kept for session
    # - Tier 3 (Insights): learn, interception - kept longer
    # - Tier 4 (Permanent): milestone - never deleted
    #
    # Usage:
    #   metabolizer = MemoryMetabolizer.new(state, event_bus: runner_event_bus)
    #   metabolizer.metabolize  # Called in Runner.observe()
    class MemoryMetabolizer
      # Default retention config
      DEFAULT_RETENTION = {
        "execution" => { max_steps: 5, summarize: true },
        "observe" => { max_steps: 3, summarize: false },
        "plan" => { max_steps: 50, summarize: false },
        "user" => { max_steps: 100, summarize: false },
        "learn" => { max_steps: 200, summarize: true },
        "interception" => { max_steps: 100, summarize: false },
        "milestone" => { permanent: true }
      }.freeze

      def initialize(state, event_bus: nil, config: {}, registry: nil)
        @state = state
        @event_bus = event_bus
        @project_path = config.fetch(:project_path, ".")
        @registry = registry  # ToolRegistry to read manifest memory settings
        @retention = load_retention_config(config.fetch(:config_path, nil))
      end

      # Main metabolism entry point
      # Called in Runner.observe() before context assembly
      # @return [Hash] Statistics about the metabolism process
      def metabolize
        stats = {
          total_events: 0,
          candidates_for_summary: 0,
          summarized: 0,
          deleted: 0,
          errors: 0
        }

        begin
          # Step 1: Get trigger conditions
          max_chars = fetch_config("state_management.max_state_chars") || 100000
          recent_n = fetch_config("state_management.recent_events_n") || 20
          
          # Step 2: Check if metabolism is needed
          total_chars = @state.send(:get_first_value, "SELECT COALESCE(SUM(LENGTH(payload)), 0) FROM events").to_i
          event_count = @state.send(:get_first_value, "SELECT COUNT(*) FROM events").to_i
          
          stats[:total_events] = event_count
          
          should_metabolize = total_chars > max_chars || event_count > recent_n * 5
          
          return stats unless should_metabolize && event_count > recent_n

          # Notify start of metabolism
          emit_metabolism_start(event_count, total_chars)

          # Step 3: Select old events for metabolism
          offset = [recent_n - 1, 0].max
          old_events = select_old_events(offset)
          
          return stats if old_events.empty?

          # Step 4: Apply retention policy - separate by tier
          retention_result = apply_retention_policy(old_events, recent_n)
          stats[:candidates_for_summary] = retention_result[:to_summarize].size

          # Step 5: Generate metabolism summary if needed
          if retention_result[:to_summarize].any?
            summary = generate_metabolism_summary(retention_result[:to_summarize])
            if summary && !summary.empty?
              @state.commit_summary("Metabolism: #{summary}")
              stats[:summarized] = retention_result[:to_summarize].size
              emit_metabolism_summary(summary)
            end
          end

          # Step 6: Delete old events (except permanent ones)
          ids_to_delete = retention_result[:to_delete].map { |e| e["id"] }
          if ids_to_delete.any?
            delete_events(ids_to_delete)
            stats[:deleted] = ids_to_delete.size
            emit_events_deleted(stats[:deleted])
          end

        rescue StandardError => e
          stats[:errors] += 1
          $stderr.puts "[MemoryMetabolizer] Error: #{e.message}"
          $stderr.puts e.backtrace.first(5).join("\n")
        end

        stats
      end

      private

      def load_retention_config(config_path)
        # Try to load from config file
        if config_path && File.exist?(config_path)
          require "yaml"
          cfg = YAML.load_file(config_path) || {}
          retention_cfg = cfg.dig("state_management", "retention")
          return retention_cfg if retention_cfg
        end
        
        # Fallback to defaults
        DEFAULT_RETENTION
      end

      def fetch_config(key_path)
        # Read from state's config cache
        @state.send(:read_config).dig(*key_path.split("."))
      rescue StandardError
        nil
      end

      def select_old_events(keep_recent_n)
        rows = @state.send(:get_first_value, 
          "SELECT id, timestamp, phase, tool, payload FROM events " \
          "WHERE id < (SELECT id FROM events ORDER BY id DESC LIMIT 1 OFFSET ?) " \
          "ORDER BY id ASC", [keep_recent_n])
        
        # Actually execute the query
        db = @state.instance_variable_get(:@db)
        rows = db.execute(
          "SELECT id, timestamp, phase, tool, payload FROM events " \
          "WHERE id < (SELECT id FROM events ORDER BY id DESC LIMIT 1 OFFSET ?) " \
          "ORDER BY id ASC", [keep_recent_n]
        )
        
        rows.map do |id, ts, phase, tool, payload|
          obj = begin JSON.parse(payload) rescue nil end
          { "id" => id, "timestamp" => ts, "phase" => phase, "tool" => tool, "payload" => obj || payload }
        end
      end

      def apply_retention_policy(events, keep_recent_n)
        to_summarize = []
        to_delete = []
        to_keep = []

        events.each do |event|
          phase = event["phase"]
          
          # Priority 1: Check if event has tool-specific retention from manifest
          policy = get_retention_policy(phase, event["tool"])
          
          if policy[:permanent] == true
            # Tier 4: Never delete
            to_keep << event
          elsif policy[:summarize] == true
            # Can be summarized before deletion
            to_summarize << event
            to_delete << event
          else
            # Just delete without summarizing
            to_delete << event
          end
        end

        { to_summarize: to_summarize, to_delete: to_delete, to_keep: to_keep }
      end

      # Get retention policy for an event
      # Priority: manifest > global config > defaults
      def get_retention_policy(phase, tool_name = nil)
        # Try to get from tool manifest first
        if tool_name && @registry
          manifest_policy = get_manifest_retention(tool_name)
          return manifest_policy if manifest_policy
        end
        
        # Fallback to global config
        @retention[phase] || { max_steps: 50, summarize: false }
      end

      # Read retention policy from tool manifest
      def get_manifest_retention(tool_name)
        return nil unless @registry
        
        tool_data = @registry.find(tool_name)
        return nil unless tool_data
        
        manifest = tool_data[:manifest] || {}
        memory_config = manifest["memory"]
        return nil unless memory_config
        
        # Convert manifest config to retention policy format
        {
          max_steps: memory_config["max_steps"] || 50,
          summarize: memory_config["summarize"] || false,
          permanent: memory_config["permanent"] || false,
          retention: memory_config["retention"] || "working"
        }
      end

      def generate_metabolism_summary(events)
        # Check if summarization is enabled
        return nil unless fetch_config("state_management.summarization.enabled") == true

        # Get max chars for summary
        max_chars = fetch_config("state_management.summarization.max_chars") || 500

        # Use NarrativeService to generate summary
        narrative_service = NarrativeService.new(@project_path)
        summary = narrative_service.synthesize(events)

        # Truncate if needed
        summary[0, max_chars] if summary && summary.length > max_chars
        summary
      rescue StandardError => e
        $stderr.puts "[MemoryMetabolizer] Summary generation failed: #{e.message}"
        nil
      end

      def delete_events(event_ids)
        return if event_ids.empty?
        
        db = @state.instance_variable_get(:@db)
        placeholders = event_ids.map { "?" }.join(",")
        db.execute("DELETE FROM events WHERE id IN (#{placeholders})", event_ids)
      end

      # Event bus notifications
      def emit_metabolism_start(event_count, total_chars)
        return unless @event_bus
        @event_bus.emit(:metabolism_start, event_count: event_count, total_chars: total_chars)
      end

      def emit_metabolism_summary(summary)
        return unless @event_bus
        @event_bus.emit(:metabolism_summary, content: summary)
      end

      def emit_events_deleted(count)
        return unless @event_bus
        @event_bus.emit(:metabolism_complete, deleted_count: count)
      end
    end
  end
end
